TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------
# Build an Diamond Support Module
# -------------------------------

#LIBRARY_IOC += xxx

# xxxRecord.dbd will be installed into <top>/dbd
DBD += ttiEX355P.dbd
ttiEX355P_DBD += base.dbd


include $(TOP)/configure/RULES
